disabled_rules: # rule identifiers to exclude from running
  - identifier_name
  - type_name
  - generic_type_name
  - comma
  - empty_parentheses_with_trailing_closure
  - force_cast
  - vertical_parameter_alignment
  - implicit_getter
  - control_statement
  - large_tuple
  - line_length
  - colon
  - empty_enum_arguments
  - cyclomatic_complexity
  - function_body_length
  - multiline_parameters
  - function_parameter_count
  - switch_case_alignment
  - type_body_length
  - unused_closure_parameter
  - file_length
  - force_try
  - unused_optional_binding
  - todo
  - multiple_closures_with_trailing_closure
  - closure_parameter_position
  - trailing_newline
  - vertical_whitespace
  - opening_brace
  - trailing_whitespace
  - statement_position
  - trailing_semicolon
  - return_arrow_whitespace
  - redundant_string_enum_value
  - closing_brace
  - leading_whitespace
opt_in_rules:
  # somrules are only opt-in
  # Find all the available rules by running:
  # swiftlint rules
  multiline_parameters
excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Carthage
  - Pods
line_length:
  warning: 120
  error: 200
  ignores_urls: true
  ignores_function_declarations: true
  ignores_comments: true
trailing_whitespace:
  ignores_empty_lines: true
vertical_whitespace:
  max_empty_lines: 2
cyclomatic_complexity:
  warning: 12
  error: 20
